name: Peer review (students)
description: Use this template for peer review teams to leave feedback on the draft stage.
title: Peer review
body:
  - type: input
    id: team-name
    attributes:
      label: Team name
      description: "What is the name of the team conducting the review?"
      placeholder: "Example: Fly Cap"
  - type: input
    id: team-members
    attributes:
      label: Team members (netID)
      description: "Who are the members of the team conducting the review? Please list their netIDs."
      placeholder: "Example: bcs88, ahd84, kl123"
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: "Describe the goal of the project."
  - type: textarea
    id: data
    attributes:
      label: Data
      description: "Describe the data used or collected (if any)."
  - type: textarea
    id: approach
    attributes:
      label: Approach
      description: "Describe the approaches, tools, and methods that will be used."
  - type: textarea
    id: ui
    attributes:
      label: User interface
      description: "Provide feedback on the user interface. How easy/difficult was it to navigate? Did you have trouble accessing certain functionalities? Was the design appealing?"
  - type: textarea
    id: llm
    attributes:
      label: LLM output
      description: "Provide feedback on the output generated by any large language models (LLMs) used in the project. Was the output relevant, accurate, and useful? Were there any issues or limitations you observed? Where appropriate, include specific examples of user prompts and the corresponding LLM outputs."
  - type: textarea
    id: bugs
    attributes:
      label: Bugs
      description: "Report any bugs or errors you encountered while using the product. Please provide details on how to reproduce the issues."
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: "Provide constructive feedback on how the team might be able to improve their project. Aim for at least three constructive comments."
  - type: textarea
    id: aspect
    attributes:
      label: Aspect
      description: "What aspect of this project are you most interested in?"
  - type: textarea
    id: own-implementation
    attributes:
      label: Reflection on your own project
      description: "What have you learned from this team's project that you are considering implementing in your own project?"
  - type: textarea
    id: further-comments
    attributes:
      label: Further comments
      description: "Any further comments or feedback?"
